module.exports = {
  LLM_PROVIDER: 'gemini',
  ANTHROPIC_API_KEY: '',
  OPENAI_API_KEY: '',
  GEMINI_API_KEY: 'test-gemini',
  GOOGLE_MAPS_API_KEY: 'test-maps',
  DRIVING_TRIGGER_INTERVAL_MIN: '3',
  DRIVING_SPEED_THRESHOLD_KMH: '25',
  DRIVING_POI_RADIUS_M: '5000',
  WALKING_POI_RADIUS_M: '800',
  MAX_LLM_CALLS_PER_TRIP: '30',
};
